models:
  - model: D:\AI Toolbox\models\abliterated\Poro-2-8B-abliterated-v2
    parameters:
      weight: 1.0
  - model: huihui-ai/DeepSeek-R1-Distill-Llama-8B-abliterated
    parameters:
      weight: 1.0

merge_method: slerp
base_model: D:\AI Toolbox\models\abliterated\Poro-2-8B-abliterated-v2

parameters:
  t: 0.3

dtype: bfloat16
