"""
AI TOOLBOX - Core Module
========================

Core functionality including paths, UI, config, and exceptions.
"""

from .paths import (
    ToolboxPaths,
    get_paths,
    reset_paths,
    get_root,
    get_models_dir,
    get_downloads_dir,
    get_gguf_dir,
    get_loras_dir,
    get_merged_dir,
    get_library_file,
    get_llama_cpp_dir,
    get_config_dir,
    get_datasets_dir,
    get_processed_dir,
    get_benchmarks_dir,
    get_safetensors_dir,
    get_adapters_dir,
    get_runs_dir,
    get_ollama_dir,
)

from .ui import (
    console,
    print_toolbox_banner,
    print_mini_banner,
    create_menu_table,
    create_model_card,
    create_info_panel,
    print_success,
    print_error,
    print_warning,
    print_info,
    print_step,
    format_size,
    format_number,
    create_progress_bar,
    create_spinner,
    clear_screen,
)

from .config import (
    ToolboxConfig,
    get_config,
    load_config,
    save_config,
    update_config,
    reset_config,
)

from .exceptions import (
    ToolboxError,
    ModelError,
    ModelNotFoundError,
    ModelDownloadError,
    ModelConversionError,
    ModelLoadError,
    TrainingError,
    DatasetError,
    DatasetNotFoundError,
    DatasetFormatError,
    TrainingConfigError,
    ConversionError,
    LlamaCppNotFoundError,
    QuantizationError,
    UnsupportedModelFormatError,
    ConfigError,
    ConfigNotFoundError,
    ConfigValidationError,
    DependencyError,
    MissingDependencyError,
    IntegrationError,
    OllamaError,
    HuggingFaceError,
)

__all__ = [
    # Paths
    'ToolboxPaths',
    'get_paths',
    'reset_paths',
    'get_root',
    'get_models_dir',
    'get_downloads_dir',
    'get_gguf_dir',
    'get_loras_dir',
    'get_merged_dir',
    'get_library_file',
    'get_llama_cpp_dir',
    'get_config_dir',
    'get_datasets_dir',
    'get_processed_dir',
    'get_benchmarks_dir',
    'get_safetensors_dir',
    'get_adapters_dir',
    'get_runs_dir',
    'get_ollama_dir',
    # UI
    'console',
    'print_toolbox_banner',
    'print_mini_banner',
    'create_menu_table',
    'create_model_card',
    'create_info_panel',
    'print_success',
    'print_error',
    'print_warning',
    'print_info',
    'print_step',
    'format_size',
    'format_number',
    'create_progress_bar',
    'create_spinner',
    'clear_screen',
    # Config
    'ToolboxConfig',
    'get_config',
    'load_config',
    'save_config',
    'update_config',
    'reset_config',
    # Exceptions
    'ToolboxError',
    'ModelError',
    'ModelNotFoundError',
    'ModelDownloadError',
    'ModelConversionError',
    'ModelLoadError',
    'TrainingError',
    'DatasetError',
    'DatasetNotFoundError',
    'DatasetFormatError',
    'TrainingConfigError',
    'ConversionError',
    'LlamaCppNotFoundError',
    'QuantizationError',
    'UnsupportedModelFormatError',
    'ConfigError',
    'ConfigNotFoundError',
    'ConfigValidationError',
    'DependencyError',
    'MissingDependencyError',
    'IntegrationError',
    'OllamaError',
    'HuggingFaceError',
]
